services:
  321vegandb:
    container_name: ${POSTGRES_HOST}
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 321vegan_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped

  321veganapi:
    container_name: 321veganapi
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - 321vegandb
    env_file:
      - .env
    environment:
      - PATH=/app/bin:$PATH
    restart: unless-stopped

  321veganpgadmin:
    container_name: 321veganpgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - 321vegandb

volumes:
  321vegan_postgres_data:
