"""add_email_change_fields_to_users

Revision ID: 073f10aae432
Revises: e41d759f95f7
Create Date: 2026-06-16 17:20:10.304738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073f10aae432'
down_revision: Union[str, None] = 'e41d759f95f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_change_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_change_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_change_expires')
    op.drop_column('users', 'email_change_token')
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
