"""b12 intake

Revision ID: 216ecef1f6d7
Revises: d29f3ea34023
Create Date: 2026-07-13 08:47:32.862262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216ecef1f6d7'
down_revision: Union[str, None] = 'd29f3ea34023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b12_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('intake_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'TWICE_WEEKLY', 'BIWEEKLY', name='b12intakefrequency'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'intake_date', name='uq_b12_intake_user_date')
    )
    op.create_index(op.f('ix_b12_intakes_id'), 'b12_intakes', ['id'], unique=False)
    op.create_index(op.f('ix_b12_intakes_intake_date'), 'b12_intakes', ['intake_date'], unique=False)
    op.create_index(op.f('ix_b12_intakes_user_id'), 'b12_intakes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_b12_intakes_user_id'), table_name='b12_intakes')
    op.drop_index(op.f('ix_b12_intakes_intake_date'), table_name='b12_intakes')
    op.drop_index(op.f('ix_b12_intakes_id'), table_name='b12_intakes')
    op.drop_table('b12_intakes')
    # ### end Alembic commands ###
