"""scan count and error response

Revision ID: d29f3ea34023
Revises: 073f10aae432
Create Date: 2026-07-08 19:10:20.278288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29f3ea34023'
down_revision: Union[str, None] = '073f10aae432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_reports', sa.Column('response', sa.String(), nullable=True))
    op.add_column('users', sa.Column('scan_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scan_count')
    op.drop_column('error_reports', 'response')
    # ### end Alembic commands ###
